apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - "apps"
  resources:
  - events
  - pods
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - intre.it
  resources:
  - websites
  verbs:
  - '*'
- apiGroups:
  - intre.it
  resources:
  - websites/status
  verbs:
  - get
  - update
  - patch